{
    'name': "Hostel Management",
    'version': '5.0',
    'summary': "Manage all activities in a hostel",
    'sequence': 1,
    'application':True,
    'depends': ['base', 'mail', 'account', 'product', 'base_automation','web'],
    'data' : [
        'security/user_groups.xml',
        'security/ir_rule_security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/ir_actions_server_data.xml',
        'data/base_automation_data.xml',
        'data/facilities_data.xml',
        'data/ir_cron_data.xml',
        'data/product_product_data.xml',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'report/leave_request_report_template.xml',
        'report/leave_report_action.xml',
        'report/student_report_template.xml',
        'report/student_report_action.xml',
        'wizard/student_report_wizard_view.xml',
        'wizard/leave_request_report_wizard_view.xml',
        'views/room_management_views.xml',
        'views/student_views.xml',
        'views/facilities_view.xml',
        'views/leave_request_views.xml',
        'views/invoice_views.xml',
        'views/cleaning_service_views.xml',
        'views/hostel_management_menu.xml',
        'views/student_form_view.xml',
    ],
}